# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e948821f589892508b0ed5f20cfe6df0c6d6b4823bf3e8ba6370d68c696c0a46b5f8885facce943292833ce58c46c271467c2ef4a862325f15698992c3f30404

test:
  secret_key_base: 29408c44ea5a71831102d5b00912baf6995a5e01da0aa20ca0424fff30ff80c929871691de6e436e7a793ee6f53b3c7e96dc2928cebeba99b7d024148c3d5e16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
